# Generated by Django 5.1 on 2024-12-04 07:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EqptStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EqptType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('features', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EqptTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AIIAP Lahore', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('hr', 'Human Resources'), ('finance', 'Finance'), ('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales')], max_length=20)),
                ('salary', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('made_in', models.CharField(blank=True, max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, max_length=500)),
                ('stp_status', models.CharField(choices=[('p', 'Pass'), ('f', 'Fail')], default='Pass', max_length=200)),
                ('date_of_manufacturing', models.DateField(blank=True)),
                ('remarks', models.TextField(blank=True, max_length=400)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.airport')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='home.eqptstatus')),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='home.eqpttype')),
            ],
            options={
                'permissions': [('can_add_equipment', 'Can add equipment'), ('can_change_equipment', 'Can change equipment'), ('can_delete_equipment', 'Can delete equipment'), ('can_view_equipment', 'Can view equipment')],
            },
        ),
        migrations.CreateModel(
            name='PlaceInstallaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=200)),
                ('duty_point', models.CharField(blank=True, max_length=400)),
                ('call_sign', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.airport')),
                ('equipment_issued', models.ManyToManyField(blank=True, to='home.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='place_of_installation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='home.placeinstallaion'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('force_no', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, max_length=200)),
                ('cnic', models.PositiveBigIntegerField(unique=True)),
                ('date_of_joining_asf', models.DateField(blank=True, max_length=200)),
                ('date_of_joining_current_station', models.DateField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.airport')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 12, 4, 7, 59, 40, 692350, tzinfo=datetime.timezone.utc))),
                ('repair_type', models.CharField(choices=[('pm', 'cm')], max_length=300)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.equipment')),
                ('staff', models.ManyToManyField(to='home.staff')),
            ],
        ),
    ]
